# https://github.com/devcontainers/images/tree/main/src/javascript-node
# https://mcr.microsoft.com/v2/devcontainers/javascript-node/tags/list
# https://www.debian.org/releases/
FROM mcr.microsoft.com/devcontainers/javascript-node:1-18-bookworm

